### ISSUE TITLE
Links to gifs do not unfold

### ISSUE THREAD

**Issue by Almouro** [bitrise-io/steps-slack-message#11]
Hi guys,

Thanks for this cool step! :D
We were using it in its 2.1.0 version and were able to send gifs on succesful/failed builds.

Unfortunately, when updating to 2.3.0, the gifs do not unfold anymore :(

See below the difference: the two first messages were sent with 2.3.0 version of the step, and the two last with version 2.1.0. A green line has also been added in the body of the message (probably the cause of this :))

<img width="687" alt="screen shot 2016-10-17 at 9 07 00 pm" src="https://cloud.githubusercontent.com/assets/4534323/19451483/af5ff0f8-94ad-11e6-97f2-e0c73388983f.png">

**Comment by viktorbenei** [comment]
Yeah, I believe this is related to the change from raw text messages to Slack's attachment API in 2.2.0 and 2.3.0 - https://github.com/bitrise-io/steps-slack-message/releases - 2.2.0 had an option to use the raw text option, which was removed in 2.3.0

Do you know if link expansion can be enabled in Slack's attachment API? Or is it a text only option?

**Comment by simonmartyr** [comment]
Looking into Slack's documentation on attachments, could it not be achieved by adding the image_url parameter to be editable?
Example:  [example](https://api.slack.com/docs/messages/builder?msg=%7B%22attachments%22%3A%5B%7B%22fallback%22%3A%22Network%20traffic%20(kb%2Fs)%3A%20How%20does%20this%20look%3F%20%40slack-ops%20-%20Sent%20by%20Julie%20Dodd%20-%20https%3A%2F%2Fdatadog.com%2Fpath%2Fto%2Fevent%22%2C%22title%22%3A%22Network%20traffic%20(kb%2Fs)%22%2C%22title_link%22%3A%22https%3A%2F%2Fdatadog.com%2Fpath%2Fto%2Fevent%22%2C%22text%22%3A%22How%20does%20this%20look%3F%20%40slack-ops%20-%20Sent%20by%20Julie%20Dodd%22%2C%22image_url%22%3A%22http%3A%2F%2Fmedia1.giphy.com%2Fmedia%2FSqXjMy2AXpGXC%2Fgiphy.gif%22%2C%22color%22%3A%22%23764FA5%22%7D%5D%7D)

**Comment by viktorbenei** [comment]
That very well might work @simonmartyr - if you have the time feel free to test it & send a PR!

**Comment by viktorbenei** [comment]
Thanks @simonmartyr for the PR!

Released in v2.4.0 (https://github.com/bitrise-io/steps-slack-message/releases/tag/2.4.0) - should be available on bitrise.io too, once the publish is accepted (~10-20 mins)!
