### ISSUE TITLE
Failure informations as part of the message

### ISSUE THREAD

**Issue by agonist** [bitrise-io/steps-slack-message#12]
As circle do : 

![screen shot 2016-10-24 at 14 34 00](https://cloud.githubusercontent.com/assets/2346698/19647609/eed671f0-99f6-11e6-8366-c6b4a3aafb16.png)

it would be awesome to have some more infos in slack message about the failure. link to the build, branch, project, commit etc... Because for now you can only specify a simple message.

**Comment by viktorbenei** [comment]
> Because for now you can only specify a simple message.

which you can customize and build up a message like the one you included ;)

E.g. "Failed: build $BITRISE_BUILD_NUMBER failed on branch $BITRISE_GIT_BRANCH - commit: $BITRISE_GIT_COMMIT ..."

Just click into the Slack step's message input, and click the "Insert variable" button which appears on the right side of the input. You can find all the env vars which you can use (including previous steps' outputs).

I'll close this issue, but if there's anything not possible to do with this step, please let us know!
