### ISSUE TITLE
Add option to linkify #channel and @user

### ISSUE THREAD

**Issue by paour** [bitrise-io/steps-slack-message#13]
When the step posts to Slack, `#channel` and `@user` aren't autolinked in the text of the message, presumably because the step [doesn't instruct Slack](https://api.slack.com/docs/message-formatting#parsing_modes) to do it.

Could you add an option to enable `link_names=1` in the Webhook request?

**Comment by viktorbenei** [comment]
Great idea @paour !

Feel free to send a PR, or create a feature request at https://discuss.bitrise.io/c/feature-request to bump the priority! (we track issues here too of course, but requests at https://discuss.bitrise.io/c/feature-request with higher votes are prioritized accordingly)

**Comment by viktorbenei** [comment]
This is now implemented (https://github.com/bitrise-io/steps-slack-message/pull/22) and the latest version of the step includes this option (turned on by default).

Thanks for the feature request @paour ! :)
