### ISSUE TITLE
About adding more information to the message

### ISSUE THREAD

**Issue by gabrieloshiro** [bitrise-io/steps-slack-message#25]
Would it be possible to make more information available on the message, such as 

- commit SHA,
- branch,
- build number

?

**Comment by viktorbenei** [comment]
Sure! Just click into the Message input field -> a green **Insert Variable** button appears -> click that

And choose from the available vars ;) You can of course add as many as you like.

(Related docs: http://devcenter.bitrise.io/getting-started/manage-your-bitrise-workflow/#inserting-environment-variables-into-step-inputs )

Happy Building! :)
