### ISSUE TITLE
Send success and failure messages to separate channels

### ISSUE THREAD

**Issue by mmoczkowski** [bitrise-io/steps-slack-message#27]
The slack step is great and very flexible but I'm missing one functionality though. Most of the inputs can be defined seperately for succesful and failed builds. However, that is not true for **channel**. In other words: I want to send a message to a certain channel for succesful builds and to a different channel for failed builds.

Thanks!

**Comment by viktorbenei** [comment]
Thanks for the feature request @mmoczkowski !

This seems like a great idea, feel free to send a PR, we'd be happy to review & accept it! :)

**Comment by usmonster** [comment]
Done in v2.7.0, no? (#33)

**Comment by viktorbenei** [comment]
Indeed, thanks for the heads up @usmonster !

The `channel_on_error` input ( https://github.com/bitrise-io/steps-slack-message/blob/b1e49748fb27696d0d66a8f66f04b420c36d9e4b/step.yml#L67 ) can be used for setting a separate channel in case the build fails - closing this issue.

**Comment by fehersanyi-bitrise** [comment]
@mmoczkowski   in the latest versions, there is an `If Build Failed` part where you can set up a different channel.
