### ISSUE TITLE
Add ability to send message to different channel if build fails

### ISSUE THREAD

**Issue by alorma** [bitrise-io/steps-slack-message#31]
It would be cool if the step is able to send a message to #dev_channel in case the build fails, and #qa_channel if build is success

**Comment by usmonster** [comment]
Done in v2.7.0, no? (#33)

**Comment by fehersanyi-bitrise** [comment]
@alorma @usmonster yes, in the latest versions, there is an `If Build Failed` part where you can set up a different channel.
