### ISSUE TITLE
Channel name required in integrations

### ISSUE THREAD

**Issue by mleatherb** [bitrise-io/steps-slack-message#4]
If you do not specify a channel in the step, it fails. The webhook URL contains the channel it's supposed to post to already.

* maybe make it an optional/override.

**Comment by viktorbenei** [comment]
Implemented in https://github.com/bitrise-io/steps-slack-message/pull/8

**Comment by viktorbenei** [comment]
released in https://github.com/bitrise-io/steps-slack-message/releases/tag/2.2.0 - thanks for the feature request!
