### ISSUE TITLE
How to combine channel and username?

### ISSUE THREAD

**Issue by eric-grab** [bitrise-io/steps-slack-message#41]
In case of success build, I want to send a message to channel `#abc` not tagging anyone.
However, in case of failure, I want to send a message to the same channel, tagging `@here` or `@someguy`.

I've tried all of the following with version 2.7.3:
- `@here`
- `#abc @here`
- `* channel: #abc * username: @here`
without success
![screen shot 2018-07-04 at 11 15 51 am](https://user-images.githubusercontent.com/31608374/42254905-a6464674-7f7b-11e8-8d8f-4d368a0c7706.png)

The following instructions is very confusing:
![screen shot 2018-07-04 at 11 17 00 am](https://user-images.githubusercontent.com/31608374/42254941-d63bd448-7f7b-11e8-945e-341b2bbf1279.png)

What are those `*` characters, am I supposed to include them?

**Comment by viktorbenei** [comment]
Team:

> What are those * characters, am I supposed to include them?

Issue seems to be that the related `description` in `step.yml` is not proper markdown formatted list.

https://github.com/bitrise-io/steps-slack-message/blob/bc760b7c4bc26c65e752ec0a74f80d1d01f49fda/step.yml#L58

@eric-grab it's not a combination of those value, it's only one of those - see: https://github.com/bitrise-io/steps-slack-message/blob/bc760b7c4bc26c65e752ec0a74f80d1d01f49fda/step.yml#L58

Sorry for the confusion, we'll fix the markdown formatting.

**Comment by viktorbenei** [comment]
@eric-grab and to answer your question: `#abc` should work if it's a "public" channel - if that's how you see the channel in Slack.

`@here` won't work because there's no such channel, that's part of the message when you use Slack not part of the channel. I hope this helps, feel free to ask if you'd have any questions!

**Comment by trapacska** [comment]
Hey @eric-grab !

Closing the issue as it has no problems when the channel defined correctly. However it was a good catch that the wrong formatting makes the configuration hardly understandable. I've scheduled this to be fixed. Thanks! 🚀

**Comment by lszucs** [comment]
Hi @eric-grab,

We fixed the markdown formatting issue, thanks again for bringing our attention to this. :)
