### ISSUE TITLE
Guide for integrating with API token

### ISSUE THREAD

**Issue by KoCMoHaBTa** [bitrise-io/steps-slack-message#48]
Hi,

I've been using the slack step with incoming web hooks.
So far it was working properly, until the 3.0.0 release where the step requires an API token.
How can I generate an API token that i can use instead of the web hook?

**Comment by bitce** [comment]
Hi @KoCMoHaBTa we're sorry for the inconvenience, we are currently working on helping this change for users with documentation. Until then:

You have to:
1) Enter your Slack Workspace in your browser
2) Select "Apps" in the bottom left
3) Select "Manage apps" in the top left
4) Select "Custom Integrations" on the left under Manage
5) Select "Bots"

That's basically it, you have to also provide a name to the bot as well, but the API token will become available after that.

**Comment by KoCMoHaBTa** [comment]
Hi @bitce 
Thanks for the directions, but I can't see `Bots` under `Custom Integrations`
<img width="1129" alt="screenshot 2018-10-09 at 16 07 38" src="https://user-images.githubusercontent.com/1181346/46672503-47a66480-cbe0-11e8-82b3-7adbc0fb5681.png">

According to a [slack guide](https://api.slack.com/custom-integrations/bot-users) - bots, alongside with web hooks, have been deprecated and now they recommend using apps for that.

I've created a new app, but i'm still struggling with finding the correct token.
I've tried with OAuth token, Verification Token, Client Secret and Signing Secret - none of these was able to send the messages.

Any idea what i'm doing wrong?

**Comment by bitce** [comment]
Just to clarify, you are looking at the [general legacy tokens](https://api.slack.com/custom-integrations/legacy-tokens), which you are right about, but slack also offers[ more type of tokens](https://api.slack.com/docs/token-types), which this isn't true for - although I will say that the documentation they have available has been confusing around this matter.

A correction to my previous steps: The bots will only appear through this method if you already have one set up. You should be able to search for the functionality ("Bots" in the Search App Directory search bar) or alternatively reach it through the link: https://yourworkspacename.slack.com/apps/A0F7YS25R-bots

**Comment by viktorbenei** [comment]
Note: you can use `my.slack.com` as a placeholder for any team workspace url, and slack will auto-redirect it "to the right place" (the default workspace). E.g. https://yourworkspacename.slack.com/apps/A0F7YS25R-bots -> https://my.slack.com/apps/A0F7YS25R-bots

**Comment by KoCMoHaBTa** [comment]
Thanks all for the help.
I was not aware that bots were actually represented as apps in slack, never created one till now :) Thanks for the clarification @bitce 
Huge thanks for the guide @BirmacherAkos - i've managed to set it up and running and can confirm that it works.
