### ISSUE TITLE
Optional message.

### ISSUE THREAD

**Issue by htinlinn** [bitrise-io/steps-slack-message#5]
We are using this step in a workflow to run unit tests for our app. We would like this step to run only when there was an issue with the test so that we don't flood our Slack channel with "Success!" messages. Would it be possible to skip grabbing the `message` variable if the build failed?

**Comment by viktorbenei** [comment]
You can do this with a `run_if`, see: http://devcenter.bitrise.io/docs/advanced-tips-tricks-for-bitrise-cli-workflows#section-run-a-step-only-if-the-build-failed 😉

**Comment by htinlinn** [comment]
that works. thanks!
