### ISSUE TITLE
Allow multiple recipients

### ISSUE THREAD

**Issue by usmonster** [bitrise-io/steps-slack-message#53]
I would like to have my Slack notification go to multiple recipients (channels and/or users).

Can the `channel*` fields be refactored to accept *a list* of notification targets? E.g. `#build_results, $SLACK_LAST_COMMITER, @qa` (assuming `SLACK_LAST_COMMITER` is an environment variable I exported in a previous step)?

The implementation could simply to loop over this collection and send a copy of the same message to each target.

Thanks!

**Comment by lszucs** [comment]
Hi @usmonster,

Thank you for the feature request, I imported it to our official Discourse instance: https://discuss.bitrise.io/t/slack-step-allow-multiple-recipients/8482.

We are moving away from handling issues (and feature requests) on GitHub, so I recommend you to vote the Discourse topic up and follow it there.

I'll leave the GitHub issue open until the request is triaged.
