### ISSUE TITLE
Attachments [feature request]

### ISSUE THREAD

**Issue by SamuelDebruyn** [bitrise-io/steps-slack-message#6]
It would be nice if we could send an attachment together with the message. Maybe somebody wants to send the APK directly in the message or you could generate a QR code for the install page and include that one as attachment.

**Comment by viktorbenei** [comment]
Thanks for the feature request @SamuelDebruyn !

**Comment by dgranahan** [comment]
Seconded!

**Comment by viktorbenei** [comment]
Anyone, feel free to send a PR with the implementation - we'll try to allocate time for this, but we have other, higher priority tasks in our list we have to finish first.

**Comment by viktorbenei** [comment]
Also, if you don't have time to implement this you could still help us/someone who will implement it with information like:

- How the attachment would be constructed in terms of a Step input? What would be the input?
- Would there be multiple slots/inputs for multiple attachments?

**Comment by viktorbenei** [comment]
I think this was implemented in https://github.com/bitrise-io/steps-slack-message/pull/14

Should work for QR codes too.

If something's still lacking just let us know and we'll re-open this issue!
